config/routes.rb
Rails.application.routes.draw do
  get 'sales/new'
  get 'sales/done', to: 'sales#done'
  post 'sales', to: 'sales#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def new
    @sale = Sale.new
  end

  def create
    sale = Sale.new(sale_params)
    prepare_sale(sale)
    redirect_to sales_done_path
  end

  def done
    @sale = Sale.all.last
  end

private
def sale_params
  params.require(:sale).permit(:detail, :category, :value, :discount, :tax)
end

def prepare_sale(sale)
  sale.cod = Random.rand(10...100000)
  sale.value = (sale_params[:value].to_i) * (100 - sale_params[:discount].to_i)
  if sale_params[:tax].to_i == 0
    sale.total = sale.value * 1.19
    sale.tax = 19
  else
    sale.tax = 0
    sale.total = sale.value
  end
    
   sale.save
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Formulario</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sales/done.html.erb
<div class="panel panel-success">
  <div class="panel-heading">El registro fue almacenado con éxito</div>

  <table class="table">
    <tr>
    <td> ID </td>
    <td> DETALLE DE LA VENTA </td>
    <td> COD </td>
    <td> CATEGORÍA </td>
    <td> VALOR </td>
    <td> DESCUENTO </td>
    <td> IVA </td>
  </tr>
  <tr>
    <td> <%= @sale.id %> </td>
    <td> <%= @sale.detail %> </td>
    <td> <%= @sale.cod %> </td>
    <td> <%= @sale.category %> </td>
    <td> <%= @sale.value %> </td>
    <td> <%= @sale.discount %> </td>
    <td> <%= @sale.tax %></td>
  </tr>
  </table>
</div>
<%= link_to "Volver", sales_new_path %>

app/views/sales/new.html.erb
<h1> Registro de ventas </h1><br><br>

<%= form_with model: Sale.new, url: sales_path, local: true, method: 'post' do |f| %>

<div class="col-md-12 field form-group">
  	<%= f.label :detail,  "Detalle de la venta:" %>
  	<div >
  		<%= f.text_area :detail, class: 'form-control' %> <br><br>
  	</div>
</div>


<div class="col-md-4 field form-group">
	<%= f.label :category, "Categoría:" %>
	<%= f.text_field :category, class: 'form-control' %><br><br>
</div>

<div class="col-md-4 field form-group">
	<%= f.label :value, "Valor:" %>
	<%= f.number_field :value, class: 'form-control' %><br><br>
</div>

<div class="col-md-4 field form-group">
	<%= f.label :discount, "Descuento:" %>
	<%= f.number_field :discount, class: 'form-control' %><br><br>
</div>

<div class="col-md-4 field form-check">
	<%= f.label :tax, "Exento de IVA:" %>
	<%= f.check_box :tax, class: 'form-check-input' %><br><br>
</div>

<div class="col-md-4 field form-group">
	<%= f.submit "Enviar", class: 'btn btn-primary btn-lg' %>
</div>

<% end %>